# Generated by Django 6.0.3 on 2026-03-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
