# Generated by Django 6.0.3 on 2026-04-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
