# Generated by Django 6.0.3 on 2026-03-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
    ]
