# Generated by Django 6.0.1 on 2026-02-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPractise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('is_Admin', models.BooleanField(default=True)),
            ],
        ),
    ]
