# Generated by Django 6.0.1 on 2026-02-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_loginpractise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpractise',
            name='password',
            field=models.CharField(),
        ),
    ]
