# Generated by Django 6.0.1 on 2026-02-08 07:03

import product.form_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_loginpractise_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[product.form_validation.validate_less_than_0]),
        ),
    ]
