# Generated by Django 6.0.1 on 2026-02-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
